CC = g++
CFLAGS = -c -Wall# -DDEBUG
SRC_DIR = source
INC_DIR = include
OBJ_DIR = object
#LOG_DIR = logger
SOURCES := $(wildcard $(SRC_DIR)/*.cpp)
INCLUDES := $(wildcard $(INC_DIR)/*.h)
OBJECTS := $(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
EXECUTABLE = myprogram
#LOGGER_HTML = listLog

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	@$(CC) $(OBJECTS) -o $@

$(OBJECTS): $(OBJ_DIR)/%.o : $(SRC_DIR)/%.cpp $(OBJ_DIR) $(LOG_DIR)
	@$(CC) $(CFLAGS) -I$(INC_DIR) $< -o $@

$(OBJ_DIR):
	@mkdir $(OBJ_DIR)
	
#$(LOG_DIR):
#	@mkdir $(LOG_DIR)

run: $(EXECUTABLE)
	@./$(EXECUTABLE)

clean:
	@del $(OBJ_DIR)\* /F /Q
	@del $(LOG_DIR)\* /F /Q